<?php
/**
 * @file
 * Module to supply footer icons for ASC Sites.
 */

/**
 * @defgroup asc_footer
 * Module to supple field to add OPIC image.
 *
 * And finally, our module defines the widet in
 * opic_field_widget_info() and field_example_field_widget_form().
 * The widget is the form element used to receive input from the user
 * when the field is being populated.
 *
 * @see field_types
 * @see field
 */

/**
 * Implements hook_menu().
 *
 * Provides a simple user interface that tells the developer where to go.
 */
function asc_wysiwyg_spellcheck_wysiwyg_editor_settings_alter(&$settings, $context) {
    if($context['profile']->editor == 'ckeditor') {
          $settings['disableNativeSpellChecker'] = false;
            }
    dsm($settings);
}
